### ISSUE TITLE
reading model error：TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by xlands** [openai/shap-e#11]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ede563c5d4cb>", line 1, in <module>
    runfile('/Users//project/shap-e/give_it_a_try.py', wdir='/Users//project/shap-e')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users//project/shap-e/give_it_a_try.py", line 11, in <module>
    xm = load_model('transmitter', device=device)
  File "/Users//project/shap-e/shap_e/models/download.py", line 144, in load_model
    from .configs import model_from_config
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users//project/shap-e/shap_e/models/configs.py", line 20, in <module>
    from shap_e.models.nerstf.mlp import MLPDensitySDFModel, MLPNeRSTFModel
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users//project/shap-e/shap_e/models/nerstf/mlp.py", line 7, in <module>
    from shap_e.models.stf.mlp import MLPModel
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users//project/shap-e/shap_e/models/stf/mlp.py", line 14, in <module>
    from .base import Model
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users//project/shap-e/shap_e/models/stf/base.py", line 11, in <module>
    class Model(ABC):
  File "/Users//project/shap-e/shap_e/models/stf/base.py", line 18, in Model
    ) -> AttrDict[str, Any]:
TypeError: 'type' object is not subscriptable

**Comment by xlands** [comment]
exactly I was running /shap_e/examples/sample_text_to_3d.ipynb.
I copied it to give_it_a_try.py,then error happened at line "xm = load_model('transmitter', device=device)"

**Comment by Demkeys** [comment]
I haven't figured out exactly why this is, but I was having the same issue and googled it, and saw someone suggest using a version greater than Python 3.9. Recreated my env using Python 3.10 and then the error stopped showing up.

**Comment by endlesswho** [comment]
> I haven't figured out exactly why this is, but I was having the same issue and googled it, and saw someone suggest using a version greater than Python 3.9. Recreated my env using Python 3.10 and then the error stopped showing up.

yes, python 3.10 works

**Comment by xlands** [comment]
> I haven't figured out exactly why this is, but I was having the same issue and googled it, and saw someone suggest using a version greater than Python 3.9. Recreated my env using Python 3.10 and then the error stopped showing up.

thx，it's done

**Comment by xlands** [comment]
> > I haven't figured out exactly why this is, but I was having the same issue and googled it, and saw someone suggest using a version greater than Python 3.9. Recreated my env using Python 3.10 and then the error stopped showing up.
> 
> yes, python 3.10 works


check 

> > I haven't figured out exactly why this is, but I was having the same issue and googled it, and saw someone suggest using a version greater than Python 3.9. Recreated my env using Python 3.10 and then the error stopped showing up.
> 
> yes, python 3.10 works

python 3.10 works confirm

**Comment by xlands** [comment]
> > I haven't figured out exactly why this is, but I was having the same issue and googled it, and saw someone suggest using a version greater than Python 3.9. Recreated my env using Python 3.10 and then the error stopped showing up.
> 
> yes, python 3.10 works

python 3.10 works confirm

**Comment by eliphatfs** [comment]
For a workaround on this issue, you can try changing the header of `util/collections.py` like this (add Generic declarations):
```python
from typing import Any, Callable, Dict, List, Optional, Generic, TypeVar


KT = TypeVar("KT")
VT = TypeVar("VT")


class AttrDict(OrderedDict, Generic[KT, VT]):
...
```
