### ISSUE TITLE
Problem with PIP installation

### ISSUE THREAD

**Issue by Python-Sargent** [openai/shap-e#46]
I'm having a problem with the pip installation suggested, this is the error:

`Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/samuel/shap-e/setup.py", line 1, in <module>
          from setuptools import setup
      ImportError: cannot import name 'setup' from 'setuptools' (unknown location)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

I believe this may be a problem with my setup, but am not sure.

**Comment by Kabanosk** [comment]
Do you have the setuptools package installed? If not, try `pip install setuptools`.

**Comment by Python-Sargent** [comment]
Ok, thanks

**Comment by Python-Sargent** [comment]
I installed using Pacman, and then tried using PIP to install:

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: setuptools in /home/samuel/.local/lib/python3.10/site-packages (65.7.0)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/samuel/.local/lib/python3.10/site-packages/setuptools-65.7.0.dist-info/METADATA'

**Comment by Kabanosk** [comment]
Maybe try `python -m pip install setuptools` or `python3 -m pip install setuptools` instead of `pip install setuptools`

**Comment by yeblu** [comment]
I'm having a problem with the pip installation suggested, this is the error:
 
 error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\lulus\AppData\Local\Temp\pip-install-b9tu2zt8\clip_4957fd2496f34a3186e3579b03210aa7' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\lulus\AppData\Local\Temp\pip-install-b9tu2zt8\clip_4957fd2496f34a3186e3579b03210aa7' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jayanthd26** [comment]
`pip install -U setuptools`
`pip install -e .`
Try this once
