### ISSUE TITLE
No module named ipywidgets

### ISSUE THREAD

**Issue by Pikamander2** [openai/shap-e#71]
I'm using Windows 10 Pro (64-bit) and Python 3.9.0 (64 bit).

After downloading the shap-e-main folder and running `pip install -e .`, I tried running this import code found in the `/shap-e/blob/main/shap_e/examples/sample_text_to_3d.ipynb` file:

```
import torch

from shap_e.diffusion.sample import sample_latents
from shap_e.diffusion.gaussian_diffusion import diffusion_from_config
from shap_e.models.download import load_model, load_config
from shap_e.util.notebooks import create_pan_cameras, decode_latent_images, gif_widget
```

And got this error:

```
Traceback (most recent call last):
  File "C:\Users\Myname\Dropbox\Python\OpenAI shap-e\shap-e-main\example-test-1.py", line 6, in <module>
    from shap_e.util.notebooks import create_pan_cameras, decode_latent_images, gif_widget
  File "C:\Users\Myname\Dropbox\Python\OpenAI shap-e\shap-e-main\shap_e\util\notebooks.py", line 5, in <module>
    import ipywidgets as widgets
ModuleNotFoundError: No module named 'ipywidgets'
```

I was able to resolve this error by running `pip install ipywidgets` in Powershell.

Is it possible that there's a missing dependency in the pip setup file or something?

**Comment by Kabanosk** [comment]
I had the same problem

**Comment by jonathanhertz** [comment]
The same happened with yaml. Had to install `pyyaml` manually.

**Comment by Charltin** [comment]
I have the same error(python 3.10.7)
